package com.intuit.userbusinessprofile.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@DynamoDBTable(tableName = "BusinessProfile")
@Data
public class BusinessProfile implements Serializable {
    @DynamoDBHashKey(attributeName = "profileId")
    @DynamoDBAutoGeneratedKey
    private String profileId;

    private String companyName;

    private String legalName;

    private Address businessAddress;

    private Address legalAddress;

    private TaxIdentifiers taxIdentifiers;

    private String email;

    private String website;

    private Long createdAt;

    private Long updatedAt;

    private Long latestApprovedValidationEventTime;

    @DynamoDBVersionAttribute
    private Long version;
}
