package com.intuit.userbusinessprofile.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.annotation.Nullable;
import lombok.Data;

import java.io.Serializable;
import java.util.Set;

@DynamoDBTable(tableName = "User")
@Data
public class User implements Serializable {
    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String userId;


    @DynamoDBAttribute(attributeName = "firstName")
    private String firstName;

    @DynamoDBAttribute(attributeName = "lastName")
    private String lastName;

    @Nullable
    private String businessProfileId;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.SS)
    private Set<Product> subscribedProducts;

    private Long createdAt;

    private Long updatedAt;

    @DynamoDBVersionAttribute
    private Long version;
}
